### ISSUE TITLE
your-firebase-url-comes-here

### ISSUE THREAD

**Issue by zygimantus** [pronto-it-labs/firebase-demo#2]
The demo after clicking „Add Friend“ does not work, should I change this into something:

`private static final String FIREBASE_URL = "your-firebase-url-comes-here";`

**Comment by jsingh27** [comment]
Yes, Refer to the firebase console, select your project. Hit Database option. 
You will see a url something like this:
https://jaspreet-149205.firebaseio.com/

You can also refer to the browser address bar for project url.
